
name: Meson node  #name of nodes
on:
  - push
permissions: write-all
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@main
      - name: download and install
        run: wget
          'https://staticassets.meson.network/public/meson_cdn/v3.1.19/meson_cdn-linux-amd64.tar.gz'
          && tar -zxf meson_cdn-linux-amd64.tar.gz && rm -f
          meson_cdn-linux-amd64.tar.gz && cd ./meson_cdn-linux-amd64 && sudo
          ./service install meson_cdn
      - name: set token and config
        run: sudo ./meson_cdn config set --token=opvkvyhbbgdthqckvopswayo
          --https_port=443 --cache.size=30
      - name: start service
        run: sudo ./service start meson_cdn
      - name: Push changes
        uses: actions/checkout@v2
        with:
          repository: Github-Username/node-action
          token: ${{secrets.ACCESSTOKEN}}
